export { default as logo } from './haifisch.webp'
export { default as main } from './main.webp'
export { default as hero } from './hero.webp'
export { default as logoDark } from './haifisch-dark.webp'
export { default as market } from './market.webp'
export { default as ozon } from './ozon.webp'
export { default as marketLogo } from './market-logo.webp'
export { default as ozonLogo } from './ozon-logo.webp'
